/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import logic.models.Department;
import logic.models.Empresa;
import logic.models.Municipio;
import logic.queries.InsertData;
import logic.queries.LoadStaticData;
import logic.queries.SelectData;
import logic.queries.UpdateData;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.Objects;

/**
 * @author alexu
 */
public class EmpresasPanel extends javax.swing.JPanel {

    String user;
    boolean update;
    int empresaId;

    /**
     * Creates new form EmpresasPanel
     */
    public EmpresasPanel(String user) {
        this.user = user;
        initComponents();
        loadDepartments();
        loadGiros();
    }

    public EmpresasPanel(int empresaId, boolean update) {
        initComponents();
        this.update = update;
        this.empresaId = empresaId;
        loadDataToEdit(empresaId);
        loadGiros();
    }

    void loadDataToEdit(int empresaId) {
        jLabel1.setText("ACTUALIZAR DATOS DE LA EMPRESA");
        List<Empresa> listaEmpresa = SelectData.getCompanieById(empresaId);

        if (!listaEmpresa.isEmpty()) {
            Empresa empresa = listaEmpresa.get(0);

            txtGetNombreComercial.setText(empresa.getNombreComercial());
            txtGetNit.setText(empresa.getNit());
            txtGetDireccion.setText(empresa.getDireccion());

            loadDepartments();
            loadGiros();

            String giro = empresa.getGiroComercialObj().getId() + " - " + empresa.getGiroComercialObj().getGiro_comercial();
            System.out.println("Giro to select: " + giro);
            String departamento = empresa.getDepartmento().getId() + " - " + empresa.getDepartmento().getName();
            String municipio = empresa.getMunicipio().getId() + " - " + empresa.getMunicipio().getName();
            String distrito = empresa.getDistrito().getId() + " - " + empresa.getDistrito().getName();

            SwingUtilities.invokeLater(() -> {
                for (int i = 0; i < jComboBoxGiros.getItemCount(); i++) {
                    if (jComboBoxGiros.getItemAt(i).toString().equals(giro)) {
                        jComboBoxGiros.setSelectedIndex(i);
                        break;
                    }
                }

                for (int i = 0; i < jComboBoxDepartamentos.getItemCount(); i++) {
                    if (jComboBoxDepartamentos.getItemAt(i).toString().equals(departamento)) {
                        jComboBoxDepartamentos.setSelectedIndex(i);
                        break;
                    }
                }

                for (int i = 0; i < jComboBoxMunicipio.getItemCount(); i++) {
                    if (jComboBoxMunicipio.getItemAt(i).toString().equals(municipio)) {
                        jComboBoxMunicipio.setSelectedIndex(i);
                        break;
                    }
                }

                for (int i = 0; i < jComboBoxDistrito.getItemCount(); i++) {
                    if (jComboBoxDistrito.getItemAt(i).toString().equals(distrito)) {
                        jComboBoxDistrito.setSelectedIndex(i);
                        break;
                    }
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always1
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxGiros = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtGetNombreComercial = new javax.swing.JTextField();
        jComboBoxDepartamentos = new javax.swing.JComboBox<>();
        txtGetNit = new javax.swing.JTextField();
        jComboBoxDistrito = new javax.swing.JComboBox<>();
        jComboBoxMunicipio = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtGetDireccion = new javax.swing.JTextField();

        setBackground(new java.awt.Color(18, 56, 84));
        setPreferredSize(new java.awt.Dimension(951, 547));

        jPanel1.setBackground(new java.awt.Color(18, 56, 84));

        jLabel3.setBackground(new java.awt.Color(18, 56, 84));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIT");

        jLabel4.setBackground(new java.awt.Color(18, 56, 84));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Giro Comercial");

        jLabel5.setBackground(new java.awt.Color(18, 56, 84));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Departamento");

        jLabel6.setBackground(new java.awt.Color(18, 56, 84));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Municipio");

        jComboBoxGiros.setBackground(new java.awt.Color(153, 102, 0));
        jComboBoxGiros.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jComboBoxGiros.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxGiros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(18, 56, 84));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AGREGAR NUEVA EMPRESA");

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtGetNombreComercial.setBackground(new java.awt.Color(153, 102, 0));
        txtGetNombreComercial.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtGetNombreComercial.setForeground(new java.awt.Color(255, 255, 255));
        txtGetNombreComercial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGetNombreComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGetNombreComercialActionPerformed(evt);
            }
        });

        jComboBoxDepartamentos.setBackground(new java.awt.Color(153, 102, 0));
        jComboBoxDepartamentos.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jComboBoxDepartamentos.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxDepartamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDepartamentosActionPerformed(evt);
            }
        });

        txtGetNit.setBackground(new java.awt.Color(153, 102, 0));
        txtGetNit.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtGetNit.setForeground(new java.awt.Color(255, 255, 255));
        txtGetNit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGetNit.addKeyListener(new KeyAdapter() {

            final int MaxLength = 17;

            // Limitar la cantidad de caracteres a 17
            @Override
            public void keyTyped(KeyEvent e) {
                if (txtGetNit.getText().length() == MaxLength) {
                    e.consume();
                }
            }

            final int[] validKeys = {
                    KeyEvent.VK_BACK_SPACE, KeyEvent.VK_TAB,
                    KeyEvent.VK_0, KeyEvent.VK_1, KeyEvent.VK_2,
                    KeyEvent.VK_3, KeyEvent.VK_4, KeyEvent.VK_5,
                    KeyEvent.VK_6, KeyEvent.VK_7, KeyEvent.VK_8,
                    KeyEvent.VK_9
            };

            @Override
            public void keyPressed(KeyEvent e) {
                boolean isValidKey = false;
                for (int validKey : validKeys) {
                    if (e.getKeyCode() == validKey) {
                        isValidKey = true;
                        break;
                    }
                }

                if (!isValidKey) {
                    JOptionPane.showMessageDialog(null, "Solo se permiten números", "Error", JOptionPane.ERROR_MESSAGE);
                    e.consume();
                    return;
                }

                // Colocar guion automático cada 4, 11 y 15 dígitos
                if (e.getKeyCode() != KeyEvent.VK_BACK_SPACE && e.getKeyCode() != KeyEvent.VK_TAB) {
                    if (txtGetNit.getText().length() == 4 || txtGetNit.getText().length() == 11 || txtGetNit.getText().length() == 15) {
                        txtGetNit.setText(txtGetNit.getText() + "-");
                    }
                }
            }
        });

        jComboBoxDistrito.setBackground(new java.awt.Color(153, 102, 0));
        jComboBoxDistrito.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jComboBoxDistrito.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxDistrito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxMunicipio.setBackground(new java.awt.Color(153, 102, 0));
        jComboBoxMunicipio.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jComboBoxMunicipio.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMunicipioActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(18, 56, 84));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Distrito");

        jLabel2.setBackground(new java.awt.Color(18, 56, 84));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Comercial");

        jLabel8.setBackground(new java.awt.Color(18, 56, 84));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dirección");

        txtGetDireccion.setBackground(new java.awt.Color(153, 102, 0));
        txtGetDireccion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtGetDireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtGetDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGetDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGetDireccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 957, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(561, 561, 561)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(21, 21, 21)
                            .addComponent(txtGetNombreComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jLabel3)
                            .addGap(24, 24, 24)
                            .addComponent(txtGetNit, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jLabel4)
                            .addGap(55, 55, 55)
                            .addComponent(jComboBoxGiros, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jLabel8)
                            .addGap(104, 104, 104)
                            .addComponent(txtGetDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jLabel5)
                            .addGap(61, 61, 61)
                            .addComponent(jComboBoxDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel6)
                            .addGap(14, 14, 14)
                            .addComponent(jComboBoxMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel7)
                            .addGap(13, 13, 13)
                            .addComponent(jComboBoxDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(671, 671, 671)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 12, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(19, 19, 19)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel2))
                        .addComponent(txtGetNombreComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel3))
                        .addComponent(txtGetNit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(33, 33, 33)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel4))
                        .addComponent(jComboBoxGiros, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(64, 64, 64)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(txtGetDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(53, 53, 53)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBoxDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))))
                    .addGap(100, 100, 100)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 31, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        reloadPanel();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtGetNombreComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGetNombreComercialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGetNombreComercialActionPerformed

    private void jComboBoxMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMunicipioActionPerformed
        setjComboBoxGetDistrict(evt);
    }//GEN-LAST:event_jComboBoxMunicipioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombreComercial = this.txtGetNombreComercial.getText();
        String nit = this.txtGetNit.getText();
        String giro = Objects.requireNonNull(jComboBoxGiros.getSelectedItem()).toString();
        String departamento = Objects.requireNonNull(jComboBoxDepartamentos.getSelectedItem()).toString();
        String municipio = Objects.requireNonNull(jComboBoxMunicipio.getSelectedItem()).toString();
        String distrito = Objects.requireNonNull(jComboBoxDistrito.getSelectedItem()).toString();

        if (nombreComercial.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre de la empresa", "Error", JOptionPane.ERROR_MESSAGE);
            txtGetNombreComercial.setText("");
            txtGetNombreComercial.requestFocus();
            return;
        }

        if (nit.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el NIT de la empresa", "Error", JOptionPane.ERROR_MESSAGE);
            txtGetNit.setText("");
            txtGetNit.requestFocus();
            return;
        }

        if (!nit.matches("\\d{4}-\\d{6}-\\d{3}-\\d{1}")) {
            JOptionPane.showMessageDialog(null, "El formato del NIT es incorrecto. Debe seguir este formato: 1234-567890-123-4", "Error", JOptionPane.ERROR_MESSAGE);
            txtGetNit.setText("");
            txtGetNit.requestFocus();
            return;
        }

        if (giro.isEmpty() || giro.equals("Seleccionar giro comercial")) {
            JOptionPane.showMessageDialog(this, "Ingrese el giro comercial de la empresa", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (departamento.isEmpty() || departamento.equals("Seleccionar departamento")) {
            JOptionPane.showMessageDialog(this, "Ingrese el departamento donde se ubica la empresa", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (municipio.isEmpty() || municipio.equals("Seleccionar municipio")) {
            JOptionPane.showMessageDialog(this, "Ingrese el municipio donde se ubica la empresa", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (distrito.isEmpty() || distrito.equals("Seleccionar distrito")) {
            JOptionPane.showMessageDialog(this, "Ingrese el distrito donde se ubica la empresa", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int companyId = SelectData.getLastCompanyId();
        int userId = SelectData.getUserID(user);

        if(!update){
            if (SelectData.ValidateNIT(nit)) {
                JOptionPane.showMessageDialog(this, "El NIT ingresado ya existe", "Error", JOptionPane.ERROR_MESSAGE);
                txtGetNit.setText("");
                txtGetNit.requestFocus();
                return;
            }
        }else{
            if (SelectData.ValidateNIT(nit, companyId)) {
                JOptionPane.showMessageDialog(this, "El NIT ingresado ya existe", "Error", JOptionPane.ERROR_MESSAGE);
                txtGetNit.setText("");
                txtGetNit.requestFocus();
                return;
            }
        }

        Empresa empresa = new Empresa(companyId, nombreComercial, nit, Integer.parseInt(giro.split(" - ")[0]), txtGetDireccion.getText(), Integer.parseInt(distrito.split(" - ")[0]), userId);

        if (update){
            if (UpdateData.updateCompanyInformation(empresa, empresaId)) {
                JOptionPane.showMessageDialog(this, 
                        "Empresa actualizada exitosamente", 
                        "Éxito", 
                        JOptionPane.INFORMATION_MESSAGE
                );
                reloadPanel();
            } else {
                JOptionPane.showMessageDialog(this, 
                        "Error al actualizar la empresa", 
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }else{
            if (InsertData.saveCompanyInformation(empresa)) {
                JOptionPane.showMessageDialog(this, 
                        "Empresa agregada exitosamente", 
                        "Éxito", 
                        JOptionPane.INFORMATION_MESSAGE
                );
                reloadPanel();
            } else {
                JOptionPane.showMessageDialog(this, 
                        "Error al guardar la empresa", 
                        "Error", 
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtGetDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGetDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGetDireccionActionPerformed

    private void jComboBoxDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {
        if (jComboBoxDepartamentos.getSelectedIndex() <= 0) {
            return;
        }
        Department selectedDepartment = (Department) jComboBoxDepartamentos.getSelectedItem();
        assert selectedDepartment != null;
        String department = selectedDepartment.toString();
        if (department == null || department.equals("Seleccionar departamento")) {
            System.out.println("No hay departamento seleccionado. Esperando interacción del usuario...");
            return;
        }
        jComboBoxMunicipio.removeAllItems();
        jComboBoxDistrito.removeAllItems();
        jComboBoxMunicipio.addItem("Seleccionar municipio");
        jComboBoxDistrito.addItem("Seleccionar distrito");

        LoadStaticData.getMunicipalities(String.valueOf(selectedDepartment.getId())).forEach(municipio -> jComboBoxMunicipio.addItem(municipio));
    }

    public void setjComboBoxGetDistrict(java.awt.event.ActionEvent evt) {
        if (jComboBoxMunicipio.getSelectedIndex() <= 0) {
            return;
        }
        Municipio selectedMunicipality = (Municipio) jComboBoxMunicipio.getSelectedItem();
        if (selectedMunicipality == null) {
            System.out.println("No hay municipio seleccionado. Esperando interacción del usuario...");
            return;
        }
        jComboBoxDistrito.removeAllItems();
        jComboBoxDistrito.addItem("Seleccionar distrito");

        LoadStaticData.getDistricts(String.valueOf(selectedMunicipality.getId())).forEach(district -> jComboBoxDistrito.addItem(district));
    }

    private void loadDepartments() {
        jComboBoxDepartamentos.removeAllItems();
        jComboBoxDepartamentos.addItem("Seleccionar departamento");
        LoadStaticData.getDepartamentos().forEach(department -> jComboBoxDepartamentos.addItem(department));
    }

    private void loadGiros() {
        jComboBoxGiros.removeAllItems();
        jComboBoxGiros.addItem("Seleccionar giro comercial");
        LoadStaticData.getGiros().forEach((giro) -> jComboBoxGiros.addItem(giro));
    }
    
    void reloadPanel(){
        jPanel1.removeAll();
        EmpresasR er = new EmpresasR(user);
        er.setSize(jPanel1.getSize()); // Establecer el tamaño igual al tamaño del contenedor
        jPanel1.setLayout(new BorderLayout()); // Usar un BorderLayout
        jPanel1.add(er, BorderLayout.CENTER); // Agregar el componente en el centro
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<Object> jComboBoxDepartamentos;
    private javax.swing.JComboBox<Object> jComboBoxDistrito;
    private javax.swing.JComboBox<Object> jComboBoxGiros;
    private javax.swing.JComboBox<Object> jComboBoxMunicipio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtGetDireccion;
    private javax.swing.JTextField txtGetNit;
    private javax.swing.JTextField txtGetNombreComercial;
    // End of variables declaration//GEN-END:variables
}
