/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;
import logic.CatalogoDeCuentasDatos;
import logic.FiltroNumeros;
import logic.models.EstadoResultado;

/**
 *
 * @author diego_grb33
 */
public class estadoResultado extends javax.swing.JPanel {

    /**
     * Creates new form estadoResultado
     */
    private int empresa_id;
    private CatalogoDeCuentasDatos catalogoCuentas;
    private EstadoResultado resultado;
    public estadoResultado(int empresa_id) {
        this.empresa_id = empresa_id;
        initComponents();
        catalogoCuentas = new CatalogoDeCuentasDatos();
        cargarEstado();
        
    }
    
    private void cargarEstado(){
        resultado = catalogoCuentas.obtenerEstadoResultado(empresa_id);
        if (resultado != null) {
            lblBruto.setText(String.valueOf("$" + resultado.getUtilidad_bruta()));
            lblOperativa.setText(String.valueOf("$" + resultado.getUtilidad_operativa()));
            lblImpuesto.setText(String.valueOf("$" + resultado.getUtilidad_antes_impuestos()));
            lblNeta.setText(String.valueOf("$" + resultado.getUtilidad_neta()));
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBruto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblOperativa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblImpuesto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNeta = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Estado de Resultados");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Utilidad Bruta: ");

        lblBruto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBruto.setText("$0.00");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Utilidad Operativa:");

        lblOperativa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblOperativa.setText("$0.00");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Utilidad antes de impuestos:");

        lblImpuesto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblImpuesto.setText("$0.00");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Utilidad Neta:");

        lblNeta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNeta.setText("$0.00");

        btnActualizar.setBackground(new java.awt.Color(0, 102, 102));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actulizar información");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNeta))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblImpuesto))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBruto)
                                    .addComponent(lblOperativa)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(btnActualizar)))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblBruto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblOperativa))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblImpuesto))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblNeta))
                .addGap(67, 67, 67)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS)); // Layout vertical
        
        JLabel label1 = new JLabel("Utilidad Bruta:");
        JTextField campoBruta = new JTextField(15);
        
        JLabel label2 = new JLabel("Utilidad Operativa:");
        JTextField campoOperativa = new JTextField(15);
        
        JLabel label4 = new JLabel("Utilidad antes de impuestos:");
        JTextField campoImpuesto = new JTextField(15);
        
        JLabel label5 = new JLabel("Utilidad Neta:");
        JTextField campoNeta = new JTextField(15);
        
        FiltroNumeros filtro = new FiltroNumeros();
        
        ((AbstractDocument) campoBruta.getDocument()).setDocumentFilter(filtro);
        ((AbstractDocument) campoOperativa.getDocument()).setDocumentFilter(filtro);
        ((AbstractDocument) campoImpuesto.getDocument()).setDocumentFilter(filtro);
        ((AbstractDocument) campoNeta.getDocument()).setDocumentFilter(filtro);
        
        if(resultado != null){
            campoBruta.setText(String.valueOf(resultado.getUtilidad_bruta()));
            campoOperativa.setText(String.valueOf(resultado.getUtilidad_operativa()));
            campoImpuesto.setText(String.valueOf(resultado.getUtilidad_antes_impuestos()));
            campoNeta.setText(String.valueOf(resultado.getUtilidad_neta()));
        }
        
        panel.add(label1);
        panel.add(campoBruta);
        panel.add(label2);
        panel.add(campoOperativa);
        panel.add(label4);
        panel.add(campoImpuesto);
        panel.add(label5);
        panel.add(campoNeta);
        
        int result = JOptionPane.showConfirmDialog(null, panel, "Modificar Estado de Resultado", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            if (!campoBruta.getText().equals("") && !campoOperativa.getText().equals("") && !campoImpuesto.getText().equals("") && !campoNeta.getText().equals("")) {
                EstadoResultado estadoModificado = new EstadoResultado(Double.parseDouble(campoBruta.getText()),Double.parseDouble(campoOperativa.getText()),
                    Double.parseDouble(campoImpuesto.getText()), Double.parseDouble(campoNeta.getText()), empresa_id);
            
                if (resultado != null) {
                    
                    catalogoCuentas.modificarEstadoResultado(estadoModificado);
                    cargarEstado();
                }else{
                    System.out.println("llega a anbtes de insertar");
                    catalogoCuentas.insertarEstadoResultado(estadoModificado);
                    cargarEstado();
                }
            }else{
                JOptionPane.showMessageDialog(null, "No deje campos vacios", "Informacion", JOptionPane.QUESTION_MESSAGE);
            }
            
        }
        
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBruto;
    private javax.swing.JLabel lblImpuesto;
    private javax.swing.JLabel lblNeta;
    private javax.swing.JLabel lblOperativa;
    // End of variables declaration//GEN-END:variables
}
