/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import java.awt.Component;
import java.awt.FlowLayout;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Isaac
 */
public class LibroMayor extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public LibroMayor() {
        initComponents();
    }
    public void getModel(DefaultTableModel model){
        jTableLibroMayor.setModel(model);
        
        // Ajustar el ancho automáticamente de la primera columna
        ajustarAnchoColumna1();

        // Desactivar edición en todas las celdas
        jTableLibroMayor.setDefaultEditor(Object.class, null);
        DefaultTableCellRenderer rendererEncabezado = (DefaultTableCellRenderer) jTableLibroMayor.getTableHeader().getDefaultRenderer();

        // Alinear el texto de los encabezados a la izquierda
        rendererEncabezado.setHorizontalAlignment(SwingConstants.LEFT);
        
        if (jTableLibroMayor.getColumnModel().getColumnCount() > 0) {
            jTableLibroMayor.getColumnModel().getColumn(0).setPreferredWidth(12);   // Ajuste de la columna "Fecha"
        }
        // Asegurarse de que se actualicen los cambios visualmente
        jTableLibroMayor.revalidate();
        jTableLibroMayor.repaint();
        
    }
    public void ajustarAnchoColumna1() {
        int column = 1; // La columna 1 es el índice 0
        int width = 0;
        for (int row = 0; row < jTableLibroMayor.getRowCount(); row++) {
            TableCellRenderer renderer = jTableLibroMayor.getCellRenderer(row, column);
            Component comp = jTableLibroMayor.prepareRenderer(renderer, row, column);
            width = Math.max(comp.getPreferredSize().width, width); // Obtener el tamaño más ancho
        }
        // Ajustar el ancho de la columna basado en el contenido
        jTableLibroMayor.getColumnModel().getColumn(column).setPreferredWidth(width);
    }

    public void getOcultarHaber(boolean flag){
        total.setVisible(flag);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLibroMayor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nombreCuenta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(241, 241, 240));

        jTableLibroMayor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Decripcion", "Debe", "Haber", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableLibroMayor);
        if (jTableLibroMayor.getColumnModel().getColumnCount() > 0) {
            jTableLibroMayor.getColumnModel().getColumn(0).setPreferredWidth(7);
            jTableLibroMayor.getColumnModel().getColumn(1).setPreferredWidth(500);
        }

        jLabel1.setText("Cuenta: ");

        nombreCuenta.setText("Efectivo");

        jLabel2.setText("Saldo en la cuenta:");

        total.setText("$0.00");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(total)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreCuenta)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTable jTableLibroMayor;
    public javax.swing.JLabel nombreCuenta;
    public javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
